name: Hello world!

on:
  push:
    branches:
      - main

jobs:
  hello_world_jobs:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello to the world!
        run: |
          echo "Hello to the world!"
